version: 0.2

phases:
  build:
    commands:
      - npm install --unsafe-perm

artifacts:
  files:
    - .ebextensions/**/*
    - main.js
    - node_modules/**/*
    - src/**/*
    - server/**/*
    - package.json
    - settings.json